### ISSUE TITLE
Using customized force field for small molecules

### ISSUE THREAD

**Issue by wenchangzhou-qtx** [OpenFreeEnergy/openfe#851]
Hey @IAlibay @mikemhenry,

For small molecules, can we now using customized force fields provided by users like myself, other than gaff or espaloma?

Thanks

**Comment by mikemhenry** [comment]
We support custom force fields if they comply with the [smirnoff spec](https://docs.openforcefield.org/projects/toolkit/en/stable/users/smirnoff.html) so anything that openff makes or you create with bespoke fit should work.

**Comment by aminsagar** [comment]
@mikemhenry 
I have also been trying to use espaloma as the small molecule force field. #682 
It seems it should be possible to use espaloma #229 
Can you please give a minimal example of using espaloma?

Thanks.

**Comment by mikemhenry** [comment]
Ah! Okay yes this is supported, I don't have time right now to test this, but it should be as easy as specifying `espaloma-0.3.2` as the forcefeield you want to use, is that what you mean? 

OH! I see in #682 it looks like openmmforcefeild needs an update to support `espaloma-0.3.2` since it only supports `espaloma-0.2.2` currently. Tracking that issue here https://github.com/openmm/openmmforcefields/issues/336

**Comment by wenchangzhou-qtx** [comment]
Thanks! @mikemhenry, on this topic, is it possible to change it inside yaml file like this?
```
protocol:
  settings:
    forcefield_settings:
      small_molecule_forcefield: 'espaloma-0.2.2'
    protocol_repeats: 2
```

**Comment by mikemhenry** [comment]
Yes that should work, if it doesn't please let me know!

**Comment by wenchangzhou-qtx** [comment]
Hey @mikemhenry, thanks for checking, I just tried but in the output json file I still have the default, `openff-2.1.1` for `small_molecule_forcefield` and 3 for `protocol_repeats`, my `setting.yaml `file looks like this:
```
mapper:
  method: lomap
  # method: kartograf

network:
  method: generate_radial_network
  settings:
    central_ligand: 'lig_ejm_31'
  # method: generate_radial_network
  # method: generate_maximal_network
  # method: generate_minimal_redundant_network

protocol:
  settings:
    forcefield_settings:
      small_molecule_forcefield: 'espaloma-0.2.2'
    protocol_repeats: 2
```
The command I run is `openfe plan-rbfe-network -M tyk2_ligands.sdf -p tyk2_protein.pdb -o network_setup -s settings.yaml`
